export const MANAGER_PROFILE_UPDATE_REQUEST = 'MANAGER_PROFILE_UPDATE_REQUEST';
export const MANAGER_PROFILE_UPDATE_SUCCESS = 'MANAGER_PROFILE_UPDATE_SUCCESS';
export const MANAGER_PROFILE_UPDATE_FAIL = 'MANAGER_PROFILE_UPDATE_FAIL';
export const MANAGER_PROFILE_UPDATE_RESET = 'MANAGER_PROFILE_UPDATE_RESET';
