export const MANAGER_PROFILE_UPDATE_REQUEST = 'MANAGER_PROFILE_UPDATE_REQUEST';
export const MANAGER_PROFILE_UPDATE_SUCCESS = 'MANAGER_PROFILE_UPDATE_SUCCESS';
export const MANAGER_PROFILE_UPDATE_FAIL = 'MANAGER_PROFILE_UPDATE_FAIL';
export const MANAGER_PROFILE_UPDATE_RESET = 'MANAGER_PROFILE_UPDATE_RESET';

export const MANAGER_PROFILE_DETAILS_REQUEST =
  'MANAGER_PROFILE_DETAILS_REQUEST';
export const MANAGER_PROFILE_DETAILS_SUCCESS =
  'MANAGER_PROFILE_DETAILS_SUCCESS';
export const MANAGER_PROFILE_DETAILS_FAIL = 'MANAGER_PROFILE_DETAILS_FAIL';
export const MANAGER_PROFILE_DETAILS_RESET = 'MANAGER_PROFILE_DETAILS_RESET';

export const MANAGER_EMPLOYEES_REQUEST = 'MANAGER_EMPLOYEES_REQUEST';
export const MANAGER_EMPLOYEES_SUCCESS = 'MANAGER_EMPLOYEES_SUCCESS';
export const MANAGER_EMPLOYEES_FAIL = 'MANAGER_EMPLOYEES_FAIL';
export const MANAGER_EMPLOYEES_RESET = 'MANAGER_EMPLOYEES_RESET';
